name: publish
on: [push]
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build the discord-jira Docker image
        run: |
          docker build . --tag ghcr.io/infiniteloopcloud/discord-jira:latest
          docker run ghcr.io/infiniteloopcloud/discord-jira:latest
          docker push ghcr.io/infiniteloopcloud/discord-jira:latest